### ISSUE TITLE
pull Caddy builds from github.com

### ISSUE THREAD

**Issue by weakcamel** [caddy-ansible/caddy-ansible#45]
From maintainers of Caddy:

https://github.com/caddyserver/website/issues/245#issuecomment-1170100127

> It should build from source with xcaddy or pull from github. Automated tooling should not hit the website.

**Comment by joelnb** [comment]
Thanks. I was actually aware of this because I had a similar response from people involved in the caddy project in the past. This was when I added the ability to download from github (which now happens automatically when no plugins are selected - builds with plugins are not available there). They stopped replying without suggesting anything that would have worked as an alternative so I left in the ability to download from the website, which was the only way things worked when this role was created (not by me), in order to not break things for users.

https://caddy.community/t/caddy-2-gpg-signature/9151/5

My preference would be if the build-server could be self-hosted - I could easily provide a way for people to use it with this role. As I still don't believe that is possible any implementation using `xcaddy` to do the build would be a large and complex change to the role which I don't have time for currently. Also would bring in questions about where the build is done & new requirements for building (either on the ansible controller or the hosts installing caddy). If someone else wants to take on  the work I would be open to reviewing a PR but I am unlikely to find the time to do it myself.

**Comment by joelnb** [comment]
Others options I can see would be:

1. Making the download happen on the ansible controller.
2. Removing all download functionality and forcing the user to provide the path to a caddy binary on the ansible controller.

I really dislike option 2 & I'm not sure option 1 would be that brilliant either because it would mean we have to do the download each time - I don't think caching it on the controller like we currently do on the target host would make sense.

**Comment by weakcamel** [comment]
Yes, option (2) is pretty much making the process semi-manual which defeats the purpose.

And I can see the gotchas in case (1) as well.

**Comment by mholt** [comment]
@joelnb 

> They stopped replying without suggesting anything that would have worked as an alternative

To clarify, an alternative was suggested by Whitestrake (Matthew Fay): 

> The money to pay for the build server supporting all those people’s deployments has to come from somewhere. ... Do you think you could help on that front?

Funding would make it possible to deploy beefier, more reliable infrastructure to keep build services available for automated use. But as the software is open source, building from source is always a solid and preferred alternative if funding is not an option. We even provide [xcaddy](https://github.com/caddyserver/xcaddy) to make this easy.

The build server is literally running `xcaddy` for you, just behind an HTTP API. So if you want to self-host the build server, you really just need `xcaddy`.

Between finding funding for a build server, building from source, and providing xcaddy for free, that's all I can think of we can do to help overcome these limitations in Ansible.

**Comment by joelnb** [comment]
Hi @mholt,

I acknowledge that I probably could have done better here but I don't feel like I ignored that in my original response on that forum post:

> I’m more than happy to help if there’s something useful I can reasonably do in the limited time I have available - I like caddy and find it useful so I don’t mind contributing. What kind of help is desired? Given that there is currently a build server still I assume that is being funded from somewhere. Is it money for that funding which is required?

I also did make a change in response to this post - previously the role (which I did not create) only ever downloaded from your build server, now it downloads from github by default and only uses the build server for builds which cannot be retrieved from github (which never happens with the default options). We also avoid downloading unless it is the first time installing on a host, the caddy version has changed (always worked out from github API) or the requested packages have changed since last run.

> Funding would make it possible to deploy beefier, more reliable infrastructure to keep build services available for automated use. If we had business/enterprise sponsors paying for such infrastructure, we could make this happen.

I have no enterprise/commercial usage of caddy, I just use it on a few servers at home and configure it using ansible because I want to learn, so I don't think I can afford to contribute an amount that would make much difference to your server costs. If I do want to personally contribute some amount I guess I would have to do that via github sponsorship?

If I were a business user installing Caddy across many nodes I would not want to use the method that this role does - it is too unreliable because it requires internet access and github.com (plus your build server, depending on settings) to be up & working. As we can tell by the fact that this issue was even opened this means that things outside of the user's control can break the installation of caddy using this role. That's probably fine for a home user but not something a business would want to accept.

> But as the software is open source, building from source is always a solid and preferred alternative if funding is not an option. We even provide [xcaddy](https://github.com/caddyserver/xcaddy) to make this easy.
> 
> The build server is literally running xcaddy for you, just behind an HTTP API. So if you want to self-host the build server, you really just need xcaddy.

But if the build server is not open source there is currently no easy way for someone to host their own without implementing the API for themself. 

Is it only removing this functionality entirely that would help with your concerns or do you think there are other mitigations I could try (beyond the things I mentioned earlier to limit times where your website will be used) which would convince you that this is okay to leave in? I can see a few things I could consider doing that could possibly help:

- Build a compatible API, which would allow people to use this role with a self-hosted build server (that calls xcaddy for the build) and add support to this role to use it.
- Push people towards using a self-hosted build server if using any plugins, including notes in the README about the costs involved for you if they do use your build server & suggesting they donate if so.
- Make it so that people have to explicitly set the URL to use your build server (not default to it at all).

I'm not trying to be unreasonable so if you feel that removal of the functionality is the only thing that can work for you I will definitely seriously consider it, but it is not my preferred option.

I also said this on the forum post which I still think is true:

> Whatever I do I think while the build server is available people will try to use it for things like this so either the build server should prevent this or it should simply be accepted that it will happen. ... If I make it inconvenient to do using the role which I help maintain then someone will most likely just create a different role which makes it easy.

It's obviously fairly trivial for anyone to write a script using curl or similar which downloads the latest version from your website on all their hosts.

Even if I do make a change it might not have much impact for a while because ansible-galaxy still hasn't picked up the latest release (from months ago), meaning people downloading from there will continue to get the old version: https://galaxy.ansible.com/caddy_ansible/caddy_ansible

**Comment by mholt** [comment]
@joelnb I don't think you're unreasonable or anything. I was not criticising or claiming that you ignored anything; I just wanted to point out something in case it was missed, is all. I understand that not everyone can foot the bill for a commercial build service (reliable with SLA) -- I'm just saying that in order for us to provide such a thing, some company or companies would need to sponsor that.

And, it's not strictly that using the build server in a script is a bad thing, it's more along the lines of distributing packages and scripts to many users -- who expect it to always work -- that expectations start failing. But there's nothing wrong with writing a little bash script that runs `curl` that you run every so often on your own computer, since it doesn't affect a lot of people and expectations aren't assumed by others.

Anyway, I appreciate the perspective and the explanation. 

> I also did make a change in response to this post - previously the role (which I did not create) only ever downloaded from your build server, now it downloads from github by default and only uses the build server for builds which cannot be retrieved from github (this never happens with the default options). We also avoid downloading unless it is the first time installing on a host, the caddy version has changed (always worked out from github API) or the requested packages have changed since last run.

Sounds like a good improvement, thanks for that!

> But if the build server is not open source there is currently no easy way for someone to host their own without implementing the API for themself.

I'm emphasizing that a build server is probably not useful/needed in the general case. This has been a solved problem for decades. If you want to access programs and resources on a remote machine, there are already protocols for that. Our build server is very niche; it's basically just designed for a click-to-download page as unique as ours.

But if you really want an HTTP API, it's pretty simple to write a few lines of Go (or anything!) that decodes a request and runs `xcaddy` (or invokes its library functions directly).

I hope that makes sense. There aren't hard restrictions on what you can and can't do, it's just more about managing expectations for an undocumented API that is being used for something it wasn't intended for. I think any of your workarounds are fine (I don't personally use Ansible nor do I know of any sponsors relying on this...) -- as long as it's clear that the build server doesn't have an SLA and definitely comes "as-is" unless we get sufficient funding for it.

As another alternative, have you considered checking with Ansible to see if the requisite features can be added?

**Comment by arhue** [comment]
Looks like Caddy's build server is down. Is there any workaround for this?

```
TASK [caddy-ansible : Download Caddy] **********************************************************************************************************************
fatal: [reverseint-2]: FAILED! => {"changed": false, "dest": "/home/caddy/caddy", "elapsed": 300, "gid": 33, "group": "www-data", "mode": "0644", "msg": "Connection failure: The read operation timed out", "owner": "www-data", "size": 39231488, "state": "file", "uid": 33, "url": "https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com/caddy-dns/godaddy"}
fatal: [reverseint-1]: FAILED! => {"changed": false, "dest": "/home/caddy/caddy", "elapsed": 300, "gid": 33, "group": "www-data", "mode": "0644", "msg": "Connection failure: The read operation timed out", "owner": "www-data", "size": 39231488, "state": "file", "uid": 33, "url": "https://caddyserver.com/api/download?os=linux&arch=amd64&p=github.com/caddy-dns/godaddy"}
```

**Comment by joelnb** [comment]
I've not had much time to spend on this recently but I finally got round to implementing a basic version of what was discussed above. I haven't written anything in the README yet because I want to do more testing but I added some options in https://github.com/caddy-ansible/caddy-ansible/pull/48

And I have been using that combined with this simple Go server https://github.com/joelnb/example-caddy-build-server to avoid the need for the Caddy build server while it has been down. The code there is very basic & probably couldn't be called 'production-ready' but it does demonstrate what Matt was saying above about how simple it is to implement something that does this.

**Comment by joelnb** [comment]
@mholt apologies for taking so long to reply here. I appreciate you taking the time to reply before & it was very useful to hear your thoughts, so thanks for that.

> I hope that makes sense. There aren't hard restrictions on what you can and can't do, it's just more about managing expectations for an undocumented API that is being used for something it wasn't intended for. I think any of your workarounds are fine (I don't personally use Ansible nor do I know of any sponsors relying on this...) -- as long as it's clear that the build server doesn't have an SLA and definitely comes "as-is" unless we get sufficient funding for it.

I tried to make this clearer to users of the role by adding this note to the README a while ago:

> This causes the builds to be downloaded from https://caddyserver.com rather than using the github releases. This service is provided for free by the Caddy maintainers and if you rely on it you should consider donating. The capacity of this service is limited so if you use this role to manage Caddy across many hosts it is recommended to use a different method.

And I plan to expand on that soon now that I have another solution which I can suggest to people (that will work well with this role) and allows them to guarantee their own reliability if the limitations of this free solution will not work for them.

> I'm emphasizing that a build server is probably not useful/needed in the general case. This has been a solved problem for decades. If you want to access programs and resources on a remote machine, there are already protocols for that. Our build server is very niche; it's basically just designed for a click-to-download page as unique as ours.

I agree this is not how I would do things for a 'proper' solution - if I needed it to be very reliable I would follow a process of making a build (per combination of plugins I need) on each new Caddy version, check that into some sort of private artifact storage & then have the ansible access it from there. Or just build VM/OS images which already contain the caddy binary. That's the kind of approach I have come across more in commercial work but it seems like overkill for my few machines and being able to just run the ansible (even if I am hosting a build server for it somewhere else) is quite attractive to me because I can easily manage hosts with different combinations of plugins & keep them all up-to-date.

In the end I spent a bit of time creating a [very simple bit of Go code](https://github.com/joelnb/example-caddy-build-server) which can replicate approximately the same HTTP API you have on your download page (all the bits this role was using anyway). This means that I could just make some very minimal changes here (https://github.com/caddy-ansible/caddy-ansible/pull/48) & offer that to people who are interested. Not sure if it will be a viable solution for anyone other than my very niche case but at least I should avoid ever hitting your build server now, even with my few machines.

> As another alternative, have you considered checking with Ansible to see if the requisite features can be added?

I think ansible is flexible enough to do the build on any of:

- The target host
- The ansible controller
- Another host in the inventory that is just used for this purpose

But it's not something that we could easily model in this role without imposing a very rigid structure on users, which wouldn't be helpful because everyone tends to structure their ansible inventory differently to meet their own requirements.
