### ISSUE TITLE
Ansible Galaxy Release

### ISSUE THREAD

**Issue by b-reich** [caddy-ansible/caddy-ansible#46]
On Github version 3.1.0 is released
On Ansible Galaxy it is still verison 3.0.4.

**Comment by joelnb** [comment]
Thanks for reporting. I recently reached out on the galaxy repo about this: https://github.com/ansible/galaxy/issues/2961

I've never had access to do anything on the galaxy side but previously it was automatically being picked up when I would make a release here. Now that is no longer happening & I have not been able to force it. I also can't make a new namespace on galaxy to publish this repo under because galaxy can see it is already associated with a namespace there.

**Comment by joelnb** [comment]
This should be updated now & I have access to the namespace on the galaxy site to force any future updates that may be required.
